service: lambda-minutes

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-southeast-2

functions:
  hello:
    handler: handler.hello
    events:
     - http:
         path: /
         method: get
